# Generated by Django 2.2 on 2019-05-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_frequency', models.IntegerField()),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='savings.Savings')),
            ],
        ),
    ]
